from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion, uuid

class Migration(migrations.Migration):
    initial = True
    dependencies = [('core','0001_initial'),('catalog','0001_initial')]
    operations = [
        migrations.CreateModel('Order', fields=[('id',models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False)),('order_number',models.CharField(max_length=20,unique=True)),('status',models.CharField(max_length=20,default='pending')),('shipping_name',models.CharField(max_length=200,blank=True)),('shipping_phone',models.CharField(max_length=30,blank=True)),('shipping_address',models.CharField(max_length=400,blank=True)),('shipping_city',models.CharField(max_length=120,blank=True)),('shipping_notes',models.TextField(blank=True)),('subtotal',models.DecimalField(max_digits=14,decimal_places=2,default=Decimal('0'))),('discount_amount',models.DecimalField(max_digits=14,decimal_places=2,default=Decimal('0'))),('discount_pct',models.DecimalField(max_digits=5,decimal_places=2,default=Decimal('0'))),('coupon_code',models.CharField(max_length=50,blank=True)),('total',models.DecimalField(max_digits=14,decimal_places=2,default=Decimal('0'))),('currency',models.CharField(max_length=3,default='COP')),('stripe_payment_intent_id',models.CharField(max_length=200,blank=True)),('stripe_client_secret',models.CharField(max_length=300,blank=True)),('tns_confirmed',models.BooleanField(default=False)),('tns_confirmation_ref',models.CharField(max_length=100,blank=True)),('tns_confirmed_at',models.DateTimeField(null=True,blank=True)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('paid_at',models.DateTimeField(null=True,blank=True)),('delivered_at',models.DateTimeField(null=True,blank=True)),('cancelled_at',models.DateTimeField(null=True,blank=True)),('customer',models.ForeignKey(to='core.User',on_delete=django.db.models.deletion.PROTECT,related_name='orders')),('advisor',models.ForeignKey(to='core.User',null=True,blank=True,on_delete=django.db.models.deletion.SET_NULL,related_name='advised_orders'))], options={'db_table':'orders','ordering':['-created_at']}),
        migrations.CreateModel('OrderItem', fields=[('id',models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False)),('product_name_snapshot',models.CharField(max_length=200,blank=True)),('unit_price',models.DecimalField(max_digits=12,decimal_places=2)),('quantity',models.PositiveIntegerField(default=1)),('order',models.ForeignKey(to='orders.Order',on_delete=django.db.models.deletion.CASCADE,related_name='items')),('product',models.ForeignKey(to='catalog.Product',on_delete=django.db.models.deletion.PROTECT,related_name='order_items'))], options={'db_table':'order_items'}),
        migrations.CreateModel('Payment', fields=[('id',models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False)),('stripe_id',models.CharField(max_length=200,blank=True)),('amount',models.DecimalField(max_digits=14,decimal_places=2)),('currency',models.CharField(max_length=3,default='COP')),('status',models.CharField(max_length=20,default='requires_payment')),('raw_webhook',models.JSONField(default=dict,blank=True)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('order',models.ForeignKey(to='orders.Order',on_delete=django.db.models.deletion.CASCADE,related_name='payments'))], options={'db_table':'payments'}),
        migrations.CreateModel('RepairTicket', fields=[('id',models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False)),('ticket_number',models.CharField(max_length=20,unique=True)),('status',models.CharField(max_length=20,default='received')),('device_type',models.CharField(max_length=100)),('device_brand',models.CharField(max_length=100,blank=True)),('device_model',models.CharField(max_length=150,blank=True)),('serial_number',models.CharField(max_length=100,blank=True)),('reported_issue',models.TextField()),('diagnosis_notes',models.TextField(blank=True)),('technician_notes',models.TextField(blank=True)),('estimated_cost',models.DecimalField(max_digits=12,decimal_places=2,null=True,blank=True)),('final_cost',models.DecimalField(max_digits=12,decimal_places=2,null=True,blank=True)),('received_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('ready_at',models.DateTimeField(null=True,blank=True)),('delivered_at',models.DateTimeField(null=True,blank=True)),('customer',models.ForeignKey(to='core.User',on_delete=django.db.models.deletion.PROTECT,related_name='repair_tickets')),('technician',models.ForeignKey(to='core.User',null=True,blank=True,on_delete=django.db.models.deletion.SET_NULL,related_name='assigned_repairs'))], options={'db_table':'repair_tickets','ordering':['-received_at']}),
        migrations.CreateModel('RepairPart', fields=[('id',models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False)),('name',models.CharField(max_length=200)),('quantity',models.PositiveIntegerField(default=1)),('unit_cost',models.DecimalField(max_digits=12,decimal_places=2,default=Decimal('0'))),('created_at',models.DateTimeField(auto_now_add=True)),('ticket',models.ForeignKey(to='orders.RepairTicket',on_delete=django.db.models.deletion.CASCADE,related_name='parts')),('added_by',models.ForeignKey(to='core.User',null=True,on_delete=django.db.models.deletion.SET_NULL))], options={'db_table':'repair_parts'}),
        migrations.CreateModel('RepairImage', fields=[('id',models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False)),('image',models.ImageField(upload_to='repairs/%Y/%m/')),('caption',models.CharField(max_length=200,blank=True)),('created_at',models.DateTimeField(auto_now_add=True)),('ticket',models.ForeignKey(to='orders.RepairTicket',on_delete=django.db.models.deletion.CASCADE,related_name='images')),('uploaded_by',models.ForeignKey(to='core.User',null=True,on_delete=django.db.models.deletion.SET_NULL))], options={'db_table':'repair_images'}),
    ]
